<a href="https://colab.research.google.com/github/hgstyler/numpy_tutorial/blob/main/numpy_tutorial_0001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy Tutorial & Practice**
begins on 0616, 2022 <br>
[by 테디베어](https://teddylee777.github.io/python/numpy-tutorial) <br>
[by Justin Johnson, AI Korea](http://aikorea.org/cs231n/python-numpy-tutorial/) <br>
[by 박해선님, TensorFlow Blog](https://tensorflow.blog/%ED%95%B8%EC%A6%88%EC%98%A8-%EB%A8%B8%EC%8B%A0%EB%9F%AC%EB%8B%9D-1%EC%9E%A5-2%EC%9E%A5/%EB%84%98%ED%8C%8C%EC%9D%B4-%ED%8A%9C%ED%86%A0%EB%A6%AC%EC%96%BC/) <br>

**<import modules\>**

In [48]:
import numpy as np
import tensorflow as tf
import keras

**0001**

In [80]:
mylist1 = [1,2,3]
mylist2 = [4,5,6]
myarray1 = np.array(mylist1)
myarray2 = np.array([[1,2,3], [4,5,6]])

print(f'mylist1: {mylist1}')
print(f'myarray1: {myarray1}')
print(f'myarray1: {myarray1.T}')
print(f'myarray2: {myarray2}')
print(f'myarray2: {myarray2.T}')
print()

print(f'mylist1: {type(mylist1)}')
print(f'myarray1: {type(myarray1)}')
print(f'myarray2: {type(myarray2)}')
print()

print('myarray1')
print(f'dimension: {myarray1.ndim}')
print(f'dimension: {myarray1.T.ndim}')
print(f'shape: {myarray1.shape}')
print(f'shape: {myarray1.T.shape}')
print(f'type: {myarray1.dtype}')
print(f'size: {myarray1.size}')
print()

print('myarray2')
print(f'dimension of myarray2: {myarray2.ndim}')
print(f'shape of myarray2: {myarray2.shape}')
print(f'dimension of myarray2: {myarray2.T.ndim}')
print(f'shape of myarray2: {myarray2.T.shape}')
print(f'type: {myarray2.dtype}')
print(f'size: {myarray2.size}')
print()

mylist1: [1, 2, 3]
myarray1: [1 2 3]
myarray1: [1 2 3]
myarray2: [[1 2 3]
 [4 5 6]]
myarray2: [[1 4]
 [2 5]
 [3 6]]

mylist1: <class 'list'>
myarray1: <class 'numpy.ndarray'>
myarray2: <class 'numpy.ndarray'>

myarray1
dimension: 1
dimension: 1
shape: (3,)
shape: (3,)
type: int64
size: 3

myarray2
dimension of myarray2: 2
shape of myarray2: (2, 3)
dimension of myarray2: 2
shape of myarray2: (3, 2)
type: int64
size: 6



**0002**

In [49]:
myarray3 = np.arange(10)
print(myarray3)

myarray4 = np.linspace(1, 200, 24)
print(myarray4)

print(np.zeros(shape=(3,5)))
print(np.full(shape=(4,6), fill_value=-4.1234))
print(np.eye(6))
print(np.random.randn(5))

[0 1 2 3 4 5 6 7 8 9]
[  1.           9.65217391  18.30434783  26.95652174  35.60869565
  44.26086957  52.91304348  61.56521739  70.2173913   78.86956522
  87.52173913  96.17391304 104.82608696 113.47826087 122.13043478
 130.7826087  139.43478261 148.08695652 156.73913043 165.39130435
 174.04347826 182.69565217 191.34782609 200.        ]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[-4.1234 -4.1234 -4.1234 -4.1234 -4.1234 -4.1234]
 [-4.1234 -4.1234 -4.1234 -4.1234 -4.1234 -4.1234]
 [-4.1234 -4.1234 -4.1234 -4.1234 -4.1234 -4.1234]
 [-4.1234 -4.1234 -4.1234 -4.1234 -4.1234 -4.1234]]
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
[ 1.98797603 -0.28514469 -0.98348547  0.75617591  0.59482156]


**0003**

In [79]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(arr1[4])
print(arr1[:2])
print(arr1[2:])
print(arr1[2:4])
print(arr1[:-2])
print(arr1[-2:])
# print(arr1[6]) #out of index range
print()
arr2 = np.array([[1,2,3,4,5], 
                [6,7,8,9,10],
                [11,12,13,14,15]])
print(arr2)
print(arr2.shape)
print(arr2[2,0])
print(arr2[2][0])
print(arr2[:,1:3])
print(arr2[:2,1:3])

arr3 = np.arange(15)
print(arr3)
print(arr3.reshape(5,3))
print(arr3.reshape(3,5))
print(arr3.reshape(5,-1))
print(arr3.reshape(-1,5))

[1 2 3 4 5]
5
[1 2]
[3 4 5]
[3 4]
[1 2 3]
[4 5]

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
(3, 5)
11
11
[[ 2  3]
 [ 7  8]
 [12 13]]
[[2 3]
 [7 8]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
